### ISSUE TITLE
Можно не использовать свойство

### ISSUE THREAD

**Issue by coder1coder** [Dmitriy-Nox/CcharpForBeginers#3]
https://github.com/Dmitriy-Nox/CcharpForBeginers/blob/7fdcc90c2e4b9b962caa196c1ae86d2f94b76461/TestGitHub/Shop/Menu/MenuItem.cs#L36

NextMenuItems публичен, зачем тогда ExitNumber ?

**Comment by Dmitriy-Nox** [comment]
Вводил времянку для отладки) Да, надо убрать)
